changelog:
  exclude:
    labels:
      - not_contain_release_note
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - BREAKING_CHANGE
    - title: New Feature Released 🎉
      labels:
        - new_feature
    - title: Application Improved 🙂
      labels:
        - enhancement
    - title: Bug Fix 🤕
      labels:
        - bug
    - title: Other Changes
      labels:
        - '*'
