changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - BREAKING_CHANGE
    - title: New Feature Released 🎉
      labels:
        - new_feature
    - title: Application Improved 🙂
      labels:
        - enhancement
    - title: Bug Fix 🤕
      labels:
        - bug
    - title: Dependencies Update
      labels:
        - dependencies
        - 'major dependencies'
    - title: Documentation
      labels:
        - documentation
    - title: Build & Deployment
      labels:
        - build
