version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: ./scripts/ngrok/Node.dockerfile
    command: 'npm run dev -- --port 9000 --host'
    ports:
      - '9000:9000'
    volumes:
      - ../..:/app
  ngrok:
    image: ngrok/ngrok:latest@sha256:9821c25c2afecb4174797a0707c097efcec3223a3b43f814214ff844bf53f707
    command: 'start --all --config /etc/ngrok.yml'
    ports:
      - '4040:4040'
    volumes:
      - './ngrok.yml:/etc/ngrok.yml'
    env_file:
      - .env
