version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: ./scripts/ngrok/Node.dockerfile
    command: 'npm run dev -- --port 9000 --host'
    ports:
      - '9000:9000'
    volumes:
      - ../..:/app
  ngrok:
    image: ngrok/ngrok:latest@sha256:e286297f6e91a8be02debeab829722b1a8633a7d862e144aca3290d7cfd757e4
    command: 'start --all --config /etc/ngrok.yml'
    ports:
      - '4040:4040'
    volumes:
      - './ngrok.yml:/etc/ngrok.yml'
    env_file:
      - .env
