name: _google-app-script-deploy
on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
      environment:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - run: npm ci
        working-directory: scripts/google-app-scripts

      - name: build
        run: |
          echo "ISSUE_POST_TOKEN=${{ secrets.ISSUE_POST_TOKEN }}" >> .env
          echo "REPO_OWNER=${{ github.repository_owner }}" >> .env
          echo "REPO_NAME=${{ github.repository }}" >> .env
          npm run build
        working-directory: scripts/google-app-scripts

      - name: setup
        run: npm run ${{ inputs.target }}:setup
        working-directory: scripts/google-app-scripts
        env:
          HOME: ${{ github.workspace }}
          GAS_ACCESS_TOKEN: ${{ secrets.GAS_ACCESS_TOKEN }}
          GAS_SCOPE: ${{ secrets.GAS_SCOPE }}
          GAS_ID_TOKEN: ${{ secrets.GAS_ID_TOKEN }}
          GAS_REFRESH_TOKEN: ${{ secrets.GAS_REFRESH_TOKEN }}
          GAS_CLIENT_ID: ${{ secrets.GAS_CLIENT_ID }}
          GAS_CLIENT_SECRET: ${{ secrets.GAS_CLIENT_SECRET }}
          SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
          PARENT_ID: ${{ secrets.PARENT_ID }}

      - name: push
        run: npm run push -- -f
        working-directory: scripts/google-app-scripts
        env:
          clasp_config_auth: ${{ github.workspace }}/scripts/google-app-scripts/.clasprc.json
