name: Test
on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@master
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: setup
        run: npm ci

      # build
      - run: npm run build:ci

      # test
      - name: type check
        run: npm run check-types

      - name: test with coverage
        run: npm run coverage

      # coverage tools
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3 # v5.3.1
        with:
          files: ./packages/core/coverage/coverage-final.json,./packages/web/coverage/coverage-final.json
          fail_ci_if_error: true
          slug: tooppoo/ac6_assemble_tool
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
