name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
  workflow_call:
    inputs:
      build_only:
        type: boolean
        default: false
        required: false
      with_lighthouse:
        type: boolean
        default: false
        required: false
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@master
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: setup
        run: npm ci

      - name: Cache turbo build setup
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # CI
      - name: build
        run: |
          env_target=packages/web/.env.local
          echo "PUBLIC_REPORT_BUG_URL=${{ vars.REPORT_BUG_URL }}" >> "$env_target"
          echo "PUBLIC_REPORT_REQUEST_URL=${{ vars.REPORT_REQUEST_URL }}" >> "$env_target"
          echo "PUBLIC_LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> "$env_target"

          npm run build
        env:
          ANALYZE_MODE: static
          NODE_ENV: production

      - name: type check
        run: npm run check-types

      - name: test with coverage
        if: ${{ !inputs.build_only }}
        run: npm run coverage

      - name: lint
        if: ${{ !inputs.build_only }}
        run: npm run lint

      - name: Run Lighthouse
        if: ${{ !inputs.build_only }}
        run: |
          npm install -g @lhci/cli@0.13.x
          lhci autorun
        working-directory: packages/web
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      # coverage tools
      - name: Upload coverage reports to Codecov
        if: ${{ !inputs.build_only }}
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
        with:
          files: ./packages/core/coverage/coverage-final.json,./packages/web/coverage/coverage-final.json
          fail_ci_if_error: true
          slug: tooppoo/ac6_assemble_tool
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # artifact
      - name: archive build
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: web-${{ github.sha }}
          path: packages/web/dist
      - name: archive analyze
        if: ${{ !inputs.build_only }}
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: analyze-${{ github.sha }}
          path: ./packages/web/analyze.html

