name: Deploy
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter the version (tag) to deploy'
        required: true

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      package_name: github-pages
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODECLIMATE_TOKEN: ${{ secrets.CODECLIMATE_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      pages: write    # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: fetch app
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: dist
      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
