name: Deploy
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter the version (tag) to deploy'
        required: true
jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      package_name: app
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODECLIMATE_TOKEN: ${{ secrets.CODECLIMATE_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ inputs.tag == '' && github.ref || join('refs/tags', inputs.tag) }}
      - name: fetch app
        uses: actions/download-artifact@v4
        with:
          name: app
      - name: deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: app
