name: deploy bug-report
on:
  push:
    tags:
      - google-app-scripts/bug-report/v*.*.*

jobs:
  deploy-bug-report:
    uses: ./.github/workflows/_google-app-scripts-deploy.yml
    with:
      environment: google-app-scripts/bug-report
      target: bug-report
    secrets: inherit
