name: deploy bug-report
on:
  push:
    tags:
      - google-app-scripts/bug-report/v*.*.*

jobs:
  deploy-bug-report:
    uses: ./.github/workflows/_google-app-scripts-deploy.yml
    with:
      environment: google-app-scripts/request
      target: bug-report
    secrets:
      issuePostToken: ${{ secrets.ISSUE_POST_TOKEN }}
      scriptId: ${{ secrets.SCRIPT_ID }}
      parentId: ${{ secrets.PARENT_ID }}
