name: deploy request
on:
  push:
    tags:
      - google-app-scripts/request/v*.*.*

jobs:
  deploy-bug-report:
    uses: ./.github/workflows/_google-app-scripts-deploy.yml
    with:
      environment: google-app-scripts/request
      target: request
    secrets: inherit
