name: Lighthouse
on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # setup
      - uses: actions/checkout@master

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: fetch app
        uses: actions/download-artifact@v4
        with:
          name: web-${{ github.sha }}
          path: dist

      # run Lighthouse
      - run: npm ci && npm install -g @lhci/cli@0.13.x
      - run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
