name: Lighthouse
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: npm ci && npm install -g @lhci/cli@0.13.x
      - name: build
        run: |
          echo "VITE_REPORT_BUG_URL=${{ vars.REPORT_BUG_URL }}" >> .env.local
          echo "VITE_REPORT_REQUEST_URL=${{ vars.REPORT_REQUEST_URL }}" >> .env.local
          echo "VITE_JA_CHARS=$(npm run --silent extract-ja-chars)" >> .env.local

          npm run build-only -- --base=${{ inputs.base_url || '/' }}
        env:
          NODE_ENV: production
      - run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
