name: Codecov
on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches:
    - main
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: tooppoo/ac6_assemble_tool
