name: Test
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      base_url:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true
      CODECLIMATE_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: setup
        run: npm ci

      - name: test with coverage
        run: npm run coverage
      - name: lint
        run: npm run lint
      - name: build
        run: |
          echo "VITE_REPORT_BUG_URL=${{ vars.REPORT_BUG_URL }}" >> .env.local
          echo "VITE_REPORT_REQUEST_URL=${{ vars.REPORT_REQUEST_URL }}" >> .env.local
         
          npm run build -- --base=${{ inputs.base_url || '/' }}
        env:
          NODE_ENV: production
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          files: ./coverage/coverage-final.json
          fail_ci_if_error: true
          slug: tooppoo/ac6_assemble_tool
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: publish codeclimate
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
      - name: archive build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package_name }}
          path: dist
        if: ${{ inputs.package_name != '' }}
