name: Web Create Release
on:
  push:
    tags:
      - 'web/v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2
        with:
          # https://github.com/softprops/action-gh-release?tab=readme-ov-file#-customizing
          prerelease: true
          generate_release_notes: true
