name: Web Create Release
on:
  push:
    tags:
      - 'web/v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        with:
          # https://github.com/softprops/action-gh-release?tab=readme-ov-file#-customizing
          prerelease: true
          generate_release_notes: true
